# Generated by Django 6.1 on 2026-08-28 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Field modified (e.g. name, description, metadata, tags)', max_length=100)),
                ('previous_value', models.TextField(blank=True, help_text='Previous value before modification')),
                ('new_value', models.TextField(blank=True, help_text='New value after modification')),
                ('reason', models.CharField(blank=True, help_text='Reason for the edit', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='entities.entity')),
            ],
            options={
                'verbose_name': 'Entity Edit History',
                'verbose_name_plural': 'Entity Edit Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
