# Generated by Django 6.1 on 2026-08-28 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text='e.g. entity, review, comment', max_length=50)),
                ('content_id', models.IntegerField(help_text='Primary key of the reported item')),
                ('reason', models.CharField(choices=[('spam', 'Spam / Commercial advertising'), ('harassment', 'Harassment / Hate speech'), ('misinformation', 'Misinformation / Fabricated claims'), ('personal_info', 'Private personal info (Doxxing)'), ('abuse', 'Abuse or offensive content'), ('other', 'Other issue')], default='other', max_length=50)),
                ('details', models.TextField(blank=True, help_text='Explanation from the reporter')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved (Action Taken)')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
