# Generated by Django 6.1 on 2026-08-28 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, help_text='Overview or description of this entity')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='entities/')),
                ('primary_image_url', models.URLField(blank=True, help_text='Direct image URL if remote', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='categories.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entities', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='entities', to='entities.tag')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='entity_media/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('media_type', models.CharField(choices=[('primary', 'Primary Image'), ('cover', 'Cover / Backdrop'), ('gallery', 'Gallery Image'), ('reference', 'Reference / Screenshot')], default='gallery', max_length=50)),
                ('source', models.CharField(blank=True, help_text='Attribution or source', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='entities.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('created_by', 'Created by'), ('developed_by', 'Developed by'), ('directed_by', 'Directed by'), ('written_by', 'Written by'), ('located_in', 'Located in'), ('owned_by', 'Owned by'), ('part_of', 'Part of'), ('related_to', 'Related to'), ('inspired_by', 'Inspired by'), ('associated_with', 'Associated with')], default='related_to', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='entities.entity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='entities.entity')),
            ],
            options={
                'verbose_name': 'Entity Relationship',
                'verbose_name_plural': 'Entity Relationships',
                'ordering': ['relationship_type', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['name'], name='entities_en_name_70a53e_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['category', 'created_at'], name='entities_en_categor_32790f_idx'),
        ),
    ]
