# Generated by Django 6.1 on 2026-08-28 09:20

import apps.ratings.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Rating score from 0.5 to 5.0 in 0.5 increments', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0), apps.ratings.models.validate_half_star])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='entities.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'entity'), name='unique_user_entity_rating')],
            },
        ),
    ]
